"use client";

import { FormEvent, KeyboardEvent, useEffect, useRef, useState, useSyncExternalStore } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { Check, ChevronDown, Copy, Menu, MessageSquare, Plus, Send, Settings2, Sparkles, Trash2, X } from "lucide-react";

type Message = { id: string; role: "user" | "assistant"; content: string; createdAt: string };
type Conversation = { id: string; title: string; messages: Message[]; createdAt: string; updatedAt: string };
const starterPrompts = ["Help me plan a productive week", "Explain quantum computing simply", "Write a thoughtful project brief"];
const newConversation = (): Conversation => { const now = new Date().toISOString(); return { id: crypto.randomUUID(), title: "New conversation", messages: [], createdAt: now, updatedAt: now }; };

export default function Home() {
  const [conversations, setConversations] = useState<Conversation[]>(() => {
    if (typeof window === "undefined") return [];
    const saved = localStorage.getItem("walidu-conversations");
    if (saved) return JSON.parse(saved) as Conversation[];
    return [newConversation()];
  });
  const [activeId, setActiveId] = useState(() => conversations[0]?.id ?? "");
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [mobileOpen, setMobileOpen] = useState(false);
  const [copied, setCopied] = useState("");
  const hydrated = useSyncExternalStore(() => () => {}, () => true, () => false);
  const bottomRef = useRef<HTMLDivElement>(null);
  const active = conversations.find((conversation) => conversation.id === activeId);

  useEffect(() => { if (conversations.length) localStorage.setItem("walidu-conversations", JSON.stringify(conversations)); bottomRef.current?.scrollIntoView({ behavior: "smooth" }); }, [conversations, loading]);
  function createChat() { const fresh = newConversation(); setConversations((current) => [fresh, ...current]); setActiveId(fresh.id); setError(""); setMobileOpen(false); }
  function deleteChat(id: string) { const remaining = conversations.filter((conversation) => conversation.id !== id); if (!remaining.length) { const fresh = newConversation(); setConversations([fresh]); setActiveId(fresh.id); } else { setConversations(remaining); if (id === activeId) setActiveId(remaining[0].id); } }
  async function sendMessage(event?: FormEvent) { event?.preventDefault(); const content = input.trim(); if (!content || loading || !active) return; const userMessage: Message = { id: crypto.randomUUID(), role: "user", content, createdAt: new Date().toISOString() }; const title = active.messages.length === 0 ? content.slice(0, 34) + (content.length > 34 ? "..." : "") : active.title; const nextMessages = [...active.messages, userMessage]; setConversations((current) => current.map((conversation) => conversation.id === active.id ? { ...conversation, title, messages: nextMessages, updatedAt: userMessage.createdAt } : conversation)); setInput(""); setLoading(true); setError(""); try { const response = await fetch("/api/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ messages: nextMessages.map(({ role, content: text }) => ({ role, content: text })) }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Something went wrong."); const assistant: Message = { id: crypto.randomUUID(), role: "assistant", content: data.content, createdAt: new Date().toISOString() }; setConversations((current) => current.map((conversation) => conversation.id === active.id ? { ...conversation, messages: [...nextMessages, assistant], updatedAt: assistant.createdAt } : conversation)); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to reach Walidu AI."); } finally { setLoading(false); } }
  function handleKeyDown(event: KeyboardEvent<HTMLTextAreaElement>) { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); void sendMessage(); } }
  async function copyText(id: string, text: string) { await navigator.clipboard.writeText(text); setCopied(id); setTimeout(() => setCopied(""), 1600); }

  return <div className="app-shell">
    <aside className={`sidebar ${mobileOpen ? "sidebar-open" : ""}`}><div className="brand"><div className="brand-mark"><Sparkles size={17} /></div><span>Walidu <em>AI</em></span><button className="icon-button mobile-close" aria-label="Close menu" onClick={() => setMobileOpen(false)}><X size={18} /></button></div><button className="new-chat" onClick={createChat}><Plus size={17} /> New chat <span>⌘ K</span></button><div className="history-label">Your conversations</div><nav className="history-list" aria-label="Conversation history">{hydrated && conversations.map((conversation) => <div key={conversation.id} className={`history-item ${conversation.id === activeId ? "selected" : ""}`}><button onClick={() => { setActiveId(conversation.id); setMobileOpen(false); }}><MessageSquare size={15} /><span>{conversation.title}</span></button><button className="delete-button" aria-label={`Delete ${conversation.title}`} onClick={() => deleteChat(conversation.id)}><Trash2 size={14} /></button></div>)}</nav><div className="sidebar-bottom"><button className="sidebar-action"><Settings2 size={17} /> Settings</button><button className="sidebar-action danger" onClick={() => { conversations.forEach((conversation) => deleteChat(conversation.id)); }}><Trash2 size={17} /> Clear conversations</button><div className="profile"><div className="avatar">W</div><div><strong>Walidu</strong><small>Personal workspace</small></div><ChevronDown size={15} /></div></div></aside>
    {mobileOpen && <button className="drawer-overlay" aria-label="Close navigation" onClick={() => setMobileOpen(false)} />}<main className="chat-panel"><header className="topbar"><button className="icon-button menu-button" aria-label="Open menu" onClick={() => setMobileOpen(true)}><Menu size={20} /></button><div className="model-picker"><span className="status-dot" /> Walidu Pro <ChevronDown size={14} /></div><div className="topbar-meta">Private &amp; secure</div></header><section className="conversation" aria-live="polite">{!hydrated || !active?.messages.length ? <div className="welcome"><div className="welcome-symbol"><Sparkles size={22} /></div><p className="eyebrow">Your thinking partner</p><h1>What will we<br /><span>discover today?</span></h1><p className="welcome-copy">Ask anything, explore ideas, or turn a rough thought into something remarkable.</p><div className="prompt-grid">{starterPrompts.map((prompt) => <button key={prompt} onClick={() => setInput(prompt)}>{prompt}<span>↗</span></button>)}</div></div> : <div className="message-stack">{active.messages.map((message) => <article key={message.id} className={`message-row ${message.role}`}><div className="message-avatar">{message.role === "assistant" ? <Sparkles size={15} /> : "W"}</div><div className="message-body"><div className="message-meta"><strong>{message.role === "assistant" ? "Walidu AI" : "You"}</strong><time>{new Date(message.createdAt).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}</time></div><div className="markdown"><ReactMarkdown remarkPlugins={[remarkGfm]}>{message.content}</ReactMarkdown></div><button className="copy-response" onClick={() => void copyText(message.id, message.content)}>{copied === message.id ? <Check size={13} /> : <Copy size={13} />} {copied === message.id ? "Copied" : "Copy"}</button></div></article>)}{loading && <div className="message-row assistant"><div className="message-avatar"><Sparkles size={15} /></div><div className="typing"><i /><i /><i /></div></div>}<div ref={bottomRef} /></div>}</section><div className="composer-wrap"><div className="composer-hint">Walidu can make mistakes. Check important info.</div><form className="composer" onSubmit={sendMessage}><textarea value={input} onChange={(event) => setInput(event.target.value)} onKeyDown={handleKeyDown} placeholder="Message Walidu AI..." rows={1} aria-label="Message Walidu AI" /><button className="send-button" type="submit" disabled={!input.trim() || loading} aria-label="Send message"><Send size={17} /></button></form>{error && <div className="error-message"><span>{error}</span><button onClick={() => void sendMessage()}>Retry</button></div>}</div></main>
  </div>;
}
